version 2.1

jobs:
  notifierNouvelleVersionBuild:
    machine: true
    steps:
      - run: echo "Une nouvelle version du build pipeline est lancee."
  notifierPassagePremierTest:
    machine: true
    steps:
      - run: echo "Le test d'acceptance 1 a ete passe avec succes."
  notifierPassageDeuxiemeTest:
    machine: true
    steps:
      - run: echo "Le test d'acceptance 2 a ete passe avec succes."
  notifierPassageTests:
    machine: true
    steps:
      - run: echo "Tous les tests ont ete passe avec succes."
  notifierNouvelleVersion:
    machine: true
    steps:
      - run: echo "La nouvelle version de l'application est en ligne."
  checkoutEtTests:
    docker:
      - image: cimg/node:15.8.0
    steps:
      - checkout
      - run: echo "Tests unitaires..."
  acceptances1:
    machine: true
    steps:
      - run: echo "Tests 1 a 5"
  acceptance2:
    machine: true
    steps:
      - run: echo "Tests 5 a 10"
  deployerStaging:
    machine: true
    steps:
      - run: echo "Staging en deploiement"
  deployerProduction:
    machine: true
    steps:
      - run: echo "Production en deploiement"

workflows:
  lancerApplication:
    jobs:
      - notifierNouvelleVersionBuild